apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: three-tier-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - name: frontend
        image: likhith045/frontend:20
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://amanpathakdevops.study/api/tasks"
        ports:
        - containerPort: 3000
      
